name: Deploy Crypto Data Pipeline to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: project-64bf9e5a-8b9a-4039-85a
  REGION: us-central1
  SERVICE_NAME: crypto-data-pipeline
  REPOSITORY: crypto-pipeline-repo
  IMAGE: crypto-data-pipeline

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Auth with GCP v√≠a Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/937186435681/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "crypto-ingestion-sa@project-64bf9e5a-8b9a-4039-85a.iam.gserviceaccount.com"

      # Install gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # Auth Docker with Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      # Build & Push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest .
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest \
            --region $REGION \
            --platform managed \
            --service-account crypto-ingestion-sa@project-64bf9e5a-8b9a-4039-85a.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --set-secrets API_KEY=API_KEY:latest,PROJECT_ID=PROJECT_ID:latest
